product.service.url: PRODUCT_SERVICE_URL

spring:
  application.name: user-app
  sleuth:
    propagation:
      type: B3
    sampler:
      probability: 1.0

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
